services:
  keyvault-emulator:
    image: jamesgoulddev/azure-keyvault-emulator:latest
    build:
      context: .
    hostname: emulator.vault.azure.net
    ports:
      - 4497:4497
    volumes:
      - ./local-certs:/https/:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:4997
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/emulator.key
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/emulator.crt
