version: '3.9'

services:
  keyvault-emulator:
    image: jamesgoulddev/azure-keyvault-emulator:latest
    build:
      context: .
    hostname: azure-keyvault-emulator.vault.azure.net
    ports:
      - 4497:4497
    # volumes:
    #   - $PWD/local-certs:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:4497
      # - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/azure-keyvault-emulator.key
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/azure-keyvault-emulator.crt
