// <auto-generated />
using System;
using AzureKeyVaultEmulator.Shared.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzureKeyVaultEmulator.Shared.Migrations
{
    [DbContext(typeof(VaultContext))]
    [Migration("20260120182953_Migration_3803255d")]
    partial class Migration_3803255d
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("AzureKeyVaultEmulator.Shared.Models.Certificates.CertificateBundle", b =>
                {
                    b.Property<Guid>("PersistedId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CertificateBlob")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("CertificateContents")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("cer");

                    b.Property<string>("CertificateIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<string>("CertificateName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("kid");

                    b.Property<string>("PersistedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersistedVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("recoveryId");

                    b.Property<string>("SecretId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("sid");

                    b.Property<string>("TagsSerialized")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Tags");

                    b.Property<string>("VaultUri")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("vaultUri");

                    b.Property<string>("X509Thumbprint")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("x5t");

                    b.HasKey("PersistedId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("AzureKeyVaultEmulator.Shared.Models.Certificates.CertificatePolicy", b =>
                {
                    b.Property<Guid>("PersistedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackingLifetimeActions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<Guid>("IssuerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IssuerPersistedId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParentCertificateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersistedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersistedVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersistedId");

                    b.HasIndex("IssuerId");

                    b.HasIndex("IssuerPersistedId");

                    b.HasIndex("ParentCertificateId")
                        .IsUnique();

                    b.ToTable("CertificatePolicies");

                    b.HasAnnotation("Relational:JsonPropertyName", "policy");
                });

            modelBuilder.Entity("AzureKeyVaultEmulator.Shared.Models.Certificates.IssuerBundle", b =>
                {
                    b.Property<Guid>("PersistedId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<string>("PersistedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersistedVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("provider");

                    b.HasKey("PersistedId");

                    b.ToTable("Issuers");

                    b.HasAnnotation("Relational:JsonPropertyName", "issuer");
                });

            modelBuilder.Entity("AzureKeyVaultEmulator.Shared.Models.Certificates.Requests.CertificateContacts", b =>
                {
                    b.Property<Guid>("PersistedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackingContacts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersistedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersistedVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersistedId");

                    b.ToTable("CertificateContacts");
                });

            modelBuilder.Entity("AzureKeyVaultEmulator.Shared.Models.Keys.KeyBundle", b =>
                {
                    b.Property<Guid>("PersistedId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Managed")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("managed");

                    b.Property<string>("PersistedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersistedVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsSerialized")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Tags");

                    b.HasKey("PersistedId");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("AzureKeyVaultEmulator.Shared.Models.Secrets.SecretBundle", b =>
                {
                    b.Property<Guid>("PersistedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("contentType");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Managed")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("managed");

                    b.Property<string>("PersistedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersistedVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<string>("TagsSerialized")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Tags");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("value");

                    b.HasKey("PersistedId");

                    b.ToTable("Secrets");
                });

            modelBuilder.Entity("AzureKeyVaultEmulator.Shared.Models.Certificates.CertificateBundle", b =>
                {
                    b.OwnsOne("AzureKeyVaultEmulator.Shared.Models.Certificates.CertificateAttributes", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("PersistedId")
                                .HasColumnType("TEXT");

                            b1.Property<long>("Created")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("created");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("enabled");

                            b1.Property<long>("Expiration")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("exp");

                            b1.Property<long>("NotBefore")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("nbf");

                            b1.Property<int?>("RecoverableDays")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("recoverableDays");

                            b1.Property<string>("RecoveryLevel")
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("recoveryLevel");

                            b1.Property<long>("Updated")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("updated");

                            b1.Property<string>("Version")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("version");

                            b1.HasKey("PersistedId");

                            b1.ToTable("Certificates");

                            b1.HasJsonPropertyName("attributes");

                            b1.WithOwner()
                                .HasForeignKey("PersistedId");
                        });

                    b.Navigation("Attributes")
                        .IsRequired();
                });

            modelBuilder.Entity("AzureKeyVaultEmulator.Shared.Models.Certificates.CertificatePolicy", b =>
                {
                    b.HasOne("AzureKeyVaultEmulator.Shared.Models.Certificates.IssuerBundle", null)
                        .WithMany("Policies")
                        .HasForeignKey("IssuerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzureKeyVaultEmulator.Shared.Models.Certificates.IssuerBundle", "Issuer")
                        .WithMany()
                        .HasForeignKey("IssuerPersistedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzureKeyVaultEmulator.Shared.Models.Certificates.CertificateBundle", "CertificateBundle")
                        .WithOne("CertificatePolicy")
                        .HasForeignKey("AzureKeyVaultEmulator.Shared.Models.Certificates.CertificatePolicy", "ParentCertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AzureKeyVaultEmulator.Shared.Models.Certificates.CertificateAttributes", "CertificateAttributes", b1 =>
                        {
                            b1.Property<Guid>("PersistedId")
                                .HasColumnType("TEXT");

                            b1.Property<long>("Created")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("created");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("enabled");

                            b1.Property<long>("Expiration")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("exp");

                            b1.Property<long>("NotBefore")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("nbf");

                            b1.Property<int?>("RecoverableDays")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("recoverableDays");

                            b1.Property<string>("RecoveryLevel")
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("recoveryLevel");

                            b1.Property<long>("Updated")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("updated");

                            b1.Property<string>("Version")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("version");

                            b1.HasKey("PersistedId");

                            b1.ToTable("CertificatePolicies");

                            b1.HasJsonPropertyName("attributes");

                            b1.WithOwner()
                                .HasForeignKey("PersistedId");
                        });

                    b.OwnsOne("AzureKeyVaultEmulator.Shared.Models.Certificates.X509CertificateProperties", "CertificateProperties", b1 =>
                        {
                            b1.Property<Guid>("PersistedId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("BackingEnhancedUsage")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.PrimitiveCollection<string>("BackingKeyUsage")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("key_usage");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("subject");

                            b1.Property<int>("ValidityMonths")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("validity_months");

                            b1.HasKey("PersistedId");

                            b1.ToTable("CertificatePolicies");

                            b1.HasJsonPropertyName("x509_props");

                            b1.WithOwner()
                                .HasForeignKey("PersistedId");

                            b1.OwnsOne("AzureKeyVaultEmulator.Shared.Models.Certificates.SubjectAlternativeNames", "SubjectAlternativeNames", b2 =>
                                {
                                    b2.Property<Guid>("PersistedId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("BackingDns")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("BackingEmails")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("BackingUpns")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("PersistedId");

                                    b2.ToTable("CertificatePolicies");

                                    b2.HasJsonPropertyName("sans");

                                    b2.WithOwner()
                                        .HasForeignKey("PersistedId");
                                });

                            b1.Navigation("SubjectAlternativeNames")
                                .IsRequired();
                        });

                    b.OwnsOne("AzureKeyVaultEmulator.Shared.Models.Keys.KeyProperties", "KeyProperties", b1 =>
                        {
                            b1.Property<Guid>("PersistedId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("JsonWebKeyCurveName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("crv");

                            b1.Property<string>("JsonWebKeyType")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("kty");

                            b1.Property<int>("KeySize")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("key_size");

                            b1.Property<bool>("ReuseKey")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("reuse_key");

                            b1.HasKey("PersistedId");

                            b1.ToTable("CertificatePolicies");

                            b1.HasJsonPropertyName("key_props");

                            b1.WithOwner()
                                .HasForeignKey("PersistedId");
                        });

                    b.OwnsOne("AzureKeyVaultEmulator.Shared.Models.Secrets.SecretProperties", "SecretProperies", b1 =>
                        {
                            b1.Property<Guid>("PersistedId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("contentType");

                            b1.HasKey("PersistedId");

                            b1.ToTable("CertificatePolicies");

                            b1.HasJsonPropertyName("secret_props");

                            b1.WithOwner()
                                .HasForeignKey("PersistedId");
                        });

                    b.Navigation("CertificateAttributes")
                        .IsRequired();

                    b.Navigation("CertificateBundle");

                    b.Navigation("CertificateProperties");

                    b.Navigation("Issuer");

                    b.Navigation("KeyProperties");

                    b.Navigation("SecretProperies");
                });

            modelBuilder.Entity("AzureKeyVaultEmulator.Shared.Models.Certificates.IssuerBundle", b =>
                {
                    b.OwnsOne("AzureKeyVaultEmulator.Shared.Models.Certificates.IssuerAttributes", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("PersistedId")
                                .HasColumnType("TEXT");

                            b1.Property<long>("Created")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("created");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("enabled");

                            b1.Property<long>("Expiration")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("exp");

                            b1.Property<long>("NotBefore")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("nbf");

                            b1.Property<int?>("RecoverableDays")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("recoverableDays");

                            b1.Property<string>("RecoveryLevel")
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("recoveryLevel");

                            b1.Property<long>("Updated")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("updated");

                            b1.HasKey("PersistedId");

                            b1.ToTable("Issuers");

                            b1.HasJsonPropertyName("attributes");

                            b1.WithOwner()
                                .HasForeignKey("PersistedId");
                        });

                    b.OwnsOne("AzureKeyVaultEmulator.Shared.Models.Certificates.IssuerCredentials", "Credentials", b1 =>
                        {
                            b1.Property<Guid>("PersistedId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AccountId")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("account_id");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("pwd");

                            b1.HasKey("PersistedId");

                            b1.ToTable("Issuers");

                            b1.HasJsonPropertyName("credentials");

                            b1.WithOwner()
                                .HasForeignKey("PersistedId");
                        });

                    b.OwnsOne("AzureKeyVaultEmulator.Shared.Models.Certificates.OrganisationDetails", "OrganisationDetails", b1 =>
                        {
                            b1.Property<Guid>("PersistedId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("BackingAdminDetails")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Identifier")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("id");

                            b1.HasKey("PersistedId");

                            b1.ToTable("Issuers");

                            b1.HasJsonPropertyName("org_details");

                            b1.WithOwner()
                                .HasForeignKey("PersistedId");
                        });

                    b.Navigation("Attributes")
                        .IsRequired();

                    b.Navigation("Credentials")
                        .IsRequired();

                    b.Navigation("OrganisationDetails");
                });

            modelBuilder.Entity("AzureKeyVaultEmulator.Shared.Models.Keys.KeyBundle", b =>
                {
                    b.OwnsOne("AzureKeyVaultEmulator.Shared.Models.Keys.InternalJsonWebKey", "Key", b1 =>
                        {
                            b1.Property<Guid>("PersistedId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("D")
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("d");

                            b1.Property<string>("Dp")
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("dp");

                            b1.Property<string>("Dq")
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("dq");

                            b1.Property<string>("E")
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("e");

                            b1.Property<string>("K")
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("k");

                            b1.Property<string>("KeyCurve")
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("crv");

                            b1.Property<string>("KeyHsm")
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("key_hsm");

                            b1.Property<string>("KeyIdentifier")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("kid");

                            b1.Property<string>("KeyName")
                                .HasColumnType("TEXT");

                            b1.PrimitiveCollection<string>("KeyOperations")
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("key_ops");

                            b1.Property<string>("KeyType")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("kty");

                            b1.Property<string>("KeyVersion")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("N")
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("n");

                            b1.Property<string>("P")
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("p");

                            b1.Property<string>("Q")
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("q");

                            b1.Property<string>("Qi")
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("qi");

                            b1.Property<byte[]>("RSAParametersBlob")
                                .IsRequired()
                                .HasColumnType("BLOB");

                            b1.Property<string>("X")
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("x");

                            b1.Property<string>("Y")
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("y");

                            b1.HasKey("PersistedId");

                            b1.ToTable("Keys");

                            b1.HasJsonPropertyName("key");

                            b1.WithOwner()
                                .HasForeignKey("PersistedId");
                        });

                    b.OwnsOne("AzureKeyVaultEmulator.Shared.Models.Keys.KeyAttributes", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("PersistedId")
                                .HasColumnType("TEXT");

                            b1.Property<long>("Created")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("created");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("enabled");

                            b1.Property<long>("Expiration")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("exp");

                            b1.Property<long>("NotBefore")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("nbf");

                            b1.Property<int?>("RecoverableDays")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("recoverableDays");

                            b1.Property<string>("RecoveryLevel")
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("recoveryLevel");

                            b1.Property<long>("Updated")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("updated");

                            b1.HasKey("PersistedId");

                            b1.ToTable("Keys");

                            b1.HasJsonPropertyName("attributes");

                            b1.WithOwner()
                                .HasForeignKey("PersistedId");
                        });

                    b.Navigation("Attributes")
                        .IsRequired();

                    b.Navigation("Key")
                        .IsRequired();
                });

            modelBuilder.Entity("AzureKeyVaultEmulator.Shared.Models.Secrets.SecretBundle", b =>
                {
                    b.OwnsOne("AzureKeyVaultEmulator.Shared.Models.Secrets.SecretAttributes", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("PersistedId")
                                .HasColumnType("TEXT");

                            b1.Property<long>("Created")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("created");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("enabled");

                            b1.Property<long>("Expiration")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("exp");

                            b1.Property<long>("NotBefore")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("nbf");

                            b1.Property<int?>("RecoverableDays")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("recoverableDays");

                            b1.Property<string>("RecoveryLevel")
                                .HasColumnType("TEXT")
                                .HasJsonPropertyName("recoveryLevel");

                            b1.Property<long>("Updated")
                                .HasColumnType("INTEGER")
                                .HasJsonPropertyName("updated");

                            b1.HasKey("PersistedId");

                            b1.ToTable("Secrets");

                            b1.HasJsonPropertyName("attributes");

                            b1.WithOwner()
                                .HasForeignKey("PersistedId");
                        });

                    b.Navigation("Attributes")
                        .IsRequired();
                });

            modelBuilder.Entity("AzureKeyVaultEmulator.Shared.Models.Certificates.CertificateBundle", b =>
                {
                    b.Navigation("CertificatePolicy");
                });

            modelBuilder.Entity("AzureKeyVaultEmulator.Shared.Models.Certificates.IssuerBundle", b =>
                {
                    b.Navigation("Policies");
                });
#pragma warning restore 612, 618
        }
    }
}
