name: Build and Push Latest

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  check-skip-label:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}

    steps:
      - name: Check for 'no-release' label
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            const shouldSkip = labels.includes('no-release');
            core.setOutput('skip', shouldSkip.toString());

  build-and-push:
    needs: check-skip-label
    if: needs.check-skip-label.outputs.skip != 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install SSL Certificates
        run: |
          dotnet dev-certs https --trust

      - name: Run Integration Tests
        run: |
          dotnet test

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Extract Version
        id: get_version
        run: |
          VERSION=latest

      - name: Build Docker Image
        run: |
          docker build -t jamesgoulddev/azure-keyvault-emulator:windows .

      - name: Push Docker Image
        run: |
          docker push jamesgoulddev/azure-keyvault-emulator:windows
